# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b505f4f7b6acc50afffd388227c7bdc5e56333370b0615d5eada4c3692e75cf98dd3a23fe6a11cbb323abcd0cb2a0433335186edc748135229603fbe3efd57b

test:
  secret_key_base: 37c83a912f01c3cdec6ed7f6b5e80ad460b93c751fedb132f9f7c4f08e9de1878079999d28479653d10f07d23fd0a5e040b415b79095d54a07780590ad354e3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
